# Generated by Django 4.1.6 on 2023-10-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[(1, 'Participant'), (2, 'Owner Event'), (3, 'Owner Event and Participant'), (4, 'admin')], default='', max_length=255),
        ),
    ]
