# Generated by Django 4.1.6 on 2023-10-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Participant', 'Participant'), ('Owner Event', 'Owner Event'), ('Owner Event and Participant', 'Owner Event and Participant')], default='', max_length=255),
        ),
    ]
