# Generated by Django 4.1.6 on 2023-10-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_category_user_categoriasinteres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(blank=True, default='', primary_key=True, serialize=False),
        ),
    ]
