# Generated by Django 4.1.6 on 2023-10-25 07:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categoriasInteres',
        ),
        migrations.AddField(
            model_name='user',
            name='CategoriaInteres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
