# Generated by Django 4.1.6 on 2023-10-25 07:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_categoriainteres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CategoriaInteres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
