# Generated by Django 4.1.6 on 2023-10-25 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagina', '0004_alter_evento_categorias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='evento',
            name='calificacion',
        ),
        migrations.AddField(
            model_name='evento',
            name='likes',
            field=models.ManyToManyField(related_name='evento_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
