# Generated by Django 4.1.6 on 2023-10-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_alter_comentario_options_remove_evento_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
