# Generated by Django 4.1.6 on 2023-10-25 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagina', '0006_alter_comentario_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='asistencia',
        ),
        migrations.AddField(
            model_name='evento',
            name='asistencia',
            field=models.ManyToManyField(related_name='asistencia', to=settings.AUTH_USER_MODEL),
        ),
    ]
